backend:
  name: github
  repo: tonibunaiasu/selfdezign.ro
  branch: main
  api_root: https://api.github.com
  site_domain: www.selfdezign.ro
  base_url: https://auth.decapcms.vercel.app

media_folder: client/public/images
public_folder: /images

collections:
  - name: team
    label: Team Members
    folder: client/src/pages
    create: false
    slug: '{{slug}}'
    files:
      - file: client/src/pages/Team.tsx
        label: Team Members
        name: team
        fields:
          - { label: 'Team Data', name: 'body', widget: 'code', default_language: 'typescript' }

  - name: pages
    label: Pages
    folder: client/src/pages
    create: true
    slug: '{{slug}}'
    extension: tsx
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
